version: "3"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    links:
      - mariadb
  mariadb:
    image: mariadb
    restart: 'always'
    volumes: 
      - /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "juve"
      MYSQL_DATABASE: "exo3"
      MYSQL_USER: "delpiero"
      MYSQL_PASSWORD: "juve"
volumes:
  db_data: {}